name: Test

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: |
          echo "hello test"

      - uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run test
        run: |
          pytest

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: |
          echo "hello lint"

      - uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run lint
        run: |
          pylint app.py