name: Test

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_PASSWORD_TEST: ${{secrets.DB_PASSWORD_TEST}}
      DB_HOST_TEST: ${{secrets.DB_HOST_TEST}}
      DB_NAME_TEST: ${{secrets.DB_NAME_TEST}}
      DB_USER_TEST: ${{secrets.DB_USER_TEST}}
      DB_PORT_TEST: ${{secrets.DB_PORT_TEST}}
      SECRET_JWT: ${{secrets.SECRET_JWT}}
    steps:
      - name: Echo message
        run: |
          echo "hello test"

      - uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run test
        run: |
          pytest

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: |
          echo "hello lint"

      - uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run lint
        run: |
          pylint app.py

  build:
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - name: Echo message
        run: |
          echo "hello build"

      - uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t .
          echo "Change required folder to match fastapi lambda function"

      - name: Package application
        run: |
          zip -r package.zip .

      - name: Echos
        run: |
          echo "${{ secrets.AWS_ACCESS_KEY_ID }}"
      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: 'us-east-1'
          function_name: 'fastapiApp'
          zip_file: 'package.zip'