name: Test

on:
  push:
    branches:
      - main
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: |
          echo "hello pipeline"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run test and lint
        run: |
          pylint app.py
          pytest